version: "3.9"

services:
  laravel_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: laravel_app
    volumes:
      - .:/var/www/html
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    ports:
      - "9000:9000"
    depends_on:
      - laravel_redis
    networks:
      - laravel_network

  laravel_nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_app
    networks:
      - laravel_network

  laravel_redis:
    image: redis:7
    container_name: laravel_redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - laravel_network

#   laravel_postgres:
#     image: postgres:17
#     container_name: laravel_postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: laravel
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - laravel_network

#   laravel_node:
#     build:
#       context: .
#       dockerfile: docker/Dockerfile.node
#     container_name: laravel_node
#     ports:
#       - "5173:5173"
#     working_dir: /var/www/html
#     volumes:
#       - .:/var/www/html
#       - /var/www/html/node_modules
#     command: ["pnpm", "run", "build"]
#     networks:
#       - laravel_network

volumes:
  postgres_data:

networks:
  laravel_network:
    driver: bridge
